name:               "youngjin25"
description:        "development/server/day-to-day/hobby"

url:                "https://youngjin25.github.io"
author:             "Ohyoungjin"  
email:              "oyj950613@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            ""
email:              "oyj950613@gmail.com"
github:             "youngjin25"
pinterest:          ""
linkedin:           ""
facebook:           "01037022720"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           2
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
