name:               "Ohyoungjin blog"
description:        "development/server/day-to-day"

url:                ""
author:             "thinker3197"
email:              "oyj950613@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "jhondoe"
email:              "oyj950613@gmail.com"
github:             "youngjinblog"
pinterest:          "jhondoe"
linkedin:           "false"
facebook:           "fairy777kr"

disqus_shortname:   "youngjinblog"

background:         "![default](https://user-images.githubusercontent.com/46802319/51885887-d7ab2c80-23d0-11e9-8763-e9cdd9986266.jpg)
"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
